### ISSUE TITLE
Japanese boxart missing

### ISSUE THREAD

**Issue by andiandi13** [libretro-thumbnails/Nintendo_-_Game_Boy#3]
Why are every GB japanese boxart replaced by international boxart (US, Europe...) ?

The thing is that there are games only released in Japan, and from what I saw, there is no boxart  for those gane because of the lack of alternative region image.

Can we use those beautiful Japanese cover ?

![883b300416184b6eac185820ada27ae9](https://user-images.githubusercontent.com/19387072/57142581-2b0c8c80-6dbd-11e9-81c7-cf3e04186fd2.jpg)
![135094-pocket-monsters-midori-game-boy-front-cover](https://user-images.githubusercontent.com/19387072/57142591-2fd14080-6dbd-11e9-91a8-27e779a86f67.jpg)

I have many missing cover to share but I want to know that first.

**Comment by xTMODx** [comment]
yes please update all not correct images with proper region images. The wrong ones were used as placeholder i think. Also please do that for other systems too if you can.

**Comment by andiandi13** [comment]
Alrigtht, however, I'm not familiar with pull requests. 

So may I post the all the images on a GitHub issue ? (One issue per console repository)

**Comment by xTMODx** [comment]
yes you can do that

**Comment by andiandi13** [comment]
Perfect. Thank you

**Comment by RobLoach** [comment]
Bunch have been added! Keep it up!
