### ISSUE TITLE
Issue with latest commit

### ISSUE THREAD

**Issue by xunkar** [libretro-thumbnails/Nintendo_-_Game_Boy#63]
A cover was added for Wario Blast with improper case ('featuring' lowercase instead of 'Featuring' uppercase). As a result both files are on the repo, but for some reason I can only pull one of them with Git because it believes that lowercase is a replacement of uppercase instead of two separate files. Compare:

https://github.com/libretro-thumbnails/Nintendo_-_Game_Boy/blob/master/Named_Boxarts/Wario%20Blast%20featuring%20Bomberman!%20(USA,%20Europe)%20(SGB%20Enhanced).png

vs 

https://github.com/libretro-thumbnails/Nintendo_-_Game_Boy/blob/master/Named_Boxarts/Wario%20Blast%20Featuring%20Bomberman!%20(USA,%20Europe)%20(SGB%20Enhanced).png

**Comment by RobLoach** [comment]
Thanks! Windows is not case-sensitive, so I'm glad you were able to catch this one.
